### ISSUE TITLE
[RSR-612] - COMPAS CORE - Update XSD file

### ISSUE THREAD

**Issue by DamienPERNET** [com-pas/compas-core#190]
The US purpose is to update the new COMPAS XSD file in attachement into COMPAS Core: [compas-core/scl-extension/src/main/resources/xsd at develop · com-pas/compas-core · GitHub](https://github.com/com-pas/compas-core/tree/develop/scl-extension/src/main/resources/xsd)

Impacts:

compas-core/scl-extension/src/main/bindings/scl-extensions.xjb => tSclFileType type to be updated

[SCL_CoMPAS_20221021.zip](https://github.com/com-pas/compas-core/files/10001629/SCL_CoMPAS_20221021.zip)

**Comment by dlabordus** [comment]
What is changed in the XSD? 
Because I don't see any difference for 'tSclFileType', which is already 'tCompasSclFileType'.
Also this is a old version in the ZIP File that's missing the Labels Elements we added a few weeks ago.

There is a import statement in here 
`<xs:import namespace="http://www.iec.ch/61850/2003/SCL" schemaLocation="SCL.xsd"/>`
I don't think it's a good idea to depend on the SCL XSD, because there are 3 versions of these today and we don't want to bind it to a specific version.
And where is that import needed for?

@Sander3003

**Comment by DamienPERNET** [comment]
> The US purpose is to update the new COMPAS XSD file in attachement into COMPAS Core: [compas-core/scl-extension/src/main/resources/xsd at develop · com-pas/compas-core · GitHub](https://github.com/com-pas/compas-core/tree/develop/scl-extension/src/main/resources/xsd)
> 
> Impacts:
> 
> compas-core/scl-extension/src/main/bindings/scl-extensions.xjb => **_List of IED types_** to be updated
> 
> [SCL_CoMPAS_20221021.zip](https://github.com/com-pas/compas-core/files/10001629/SCL_CoMPAS_20221021.zip)
